---
version: '3.8'

services:
  web-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=dev-compose
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - "14333:3000"